name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - run: flutter create . --project-name=my_crm --platforms=android

      - run: flutter pub get

      - name: Fix Kotlin dependencies
        run: |
          cd android
          sed -i '/allprojects {/a\    configurations.all { resolutionStrategy.eachDependency { DependencyResolveDetails details -> if (details.requested.group == "org.jetbrains.kotlin") { details.useVersion "1.8.22" } } }' build.gradle
          cd ..

      - run: cd android && ./gradlew clean && cd ..

      - run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
